/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function generatesHashingHex(str: string, is96Bits: boolean, is32Bits: boolean): string
export function processContent(path: string): void
export function alchemyProcessing(key: string, data: string, isModular: boolean, filePath: string, pseudo: string): string
