name: Build Rust Binaries with Cross

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-linux:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - aarch64-unknown-linux-gnu
                    - aarch64-unknown-linux-musl
                    - armv7-unknown-linux-gnueabihf
                    - armv7-unknown-linux-musleabihf
                    - x86_64-unknown-linux-musl
                    - riscv64gc-unknown-linux-gnu
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions/setup-rust@v1
              with:
                  rust-version: stable

            - name: Install dependencies for cross-compilation
              run: |
                  rustup target add ${{ matrix.target }}
                  cargo install cross

            - name: Build binary for ${{ matrix.target }} using cross
              run: |
                  cross build --release --target ${{ matrix.target }}

            - name: Upload Linux artifact
              uses: actions/upload-artifact@v2
              with:
                  name: galadriel-css-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/

    build-macos:
        runs-on: macos-latest
        strategy:
            matrix:
                target:
                    - aarch64-apple-darwin
                    - universal-apple-darwin
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions/setup-rust@v1
              with:
                  rust-version: stable

            - name: Install dependencies for macOS cross-compilation
              run: |
                  rustup target add ${{ matrix.target }}
                  cargo install cross

            - name: Build binary for ${{ matrix.target }} using cross
              run: |
                  cross build --release --target ${{ matrix.target }}

            - name: Upload macOS artifact
              uses: actions/upload-artifact@v2
              with:
                  name: galadriel-css-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/

    build-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                target:
                    - aarch64-pc-windows-msvc
                    - i686-pc-windows-msvc
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions/setup-rust@v1
              with:
                  rust-version: stable

            - name: Install dependencies for Windows cross-compilation
              run: |
                  rustup target add ${{ matrix.target }}
                  cargo install cross

            - name: Build binary for ${{ matrix.target }} using cross
              run: |
                  cross build --release --target ${{ matrix.target }}

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v2
              with:
                  name: galadriel-css-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/
