name: Build and Test GaladrielCSS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    runs-on: ${{ matrix.platform == 'x86_64-pc-windows-msvc' && 'windows-latest' || ( matrix.platform == 'x86_64-apple-darwin' || matrix.platform == 'aarch64-apple-darwin' ) && 'macos-latest' || 'ubuntu-16.04' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.platform }}

      - name: Install MUSL tools (only for Linux MUSL)
        if: matrix.platform == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.platform }}

      - name: Check output directory (Linux and macOS)
        if: matrix.platform != 'x86_64-pc-windows-msvc'
        run: ls -al target/${{ matrix.platform }}/release/

      - name: Check output directory (Windows)
        if: matrix.platform == 'x86_64-pc-windows-msvc'
        run: Get-ChildItem -Force target/${{ matrix.platform }}/release/

      - name: Upload artifact (Linux, macOS)
        if: matrix.platform != 'x86_64-pc-windows-msvc'
        uses: actions/upload-artifact@v4
        with:
          name: galadrielcss-${{ matrix.platform }}
          path: target/${{ matrix.platform }}/release/galadrielcss

      - name: Upload artifact (Windows)
        if: matrix.platform == 'x86_64-pc-windows-msvc'
        uses: actions/upload-artifact@v4
        with:
          name: galadrielcss-${{ matrix.platform }}
          path: target/${{ matrix.platform }}/release/galadrielcss.exe
